### ISSUE TITLE
 Read sources from list in some format and parametrisa all sources on the list.

### ISSUE THREAD

**Issue by gigjozsa** [gigjozsa/tirific-devel#1]
We need a wrapper to fully automate the chain from source detection to source characterisation.

**Comment by gigjozsa** [comment]
As with the complete interface to Sofia, can you confirm that this is done, Peter? For the further development of the wrapper, this can then just be shifted to issue https://github.com/gigjozsa/tirific-devel/milestones/Automated%20fitting%20reimplementation .

**Comment by PeterKamphuis** [comment]
Yes, this is fully implemented into the wrapper. It reads a catalogue file which should contain a line for each galaxy with its directory name and a distance. If the pre-Produced SoFiA files should be used for the initial estimates they should also be provided in the catalogue file.

Yes can be shifted. Not sure how to do this should I close this?

**Comment by gigjozsa** [comment]
Yes, thanks. I took the honor.
