### ISSUE TITLE
Fully connect automated source finding to sofia.

### ISSUE THREAD

**Issue by gigjozsa** [gigjozsa/tirific-devel#3]

**Comment by gigjozsa** [comment]
Peter, if I understand correctly, this is already done, and will automatically covered for the translating wrapper update. I assigned you to this issue. Could you close?

**Comment by PeterKamphuis** [comment]
Yes, SoFiA can be run from inside the wrapper or a list of pre-produced SoFiA files can be supplied to the code if the user wants to fine tune the SoFiA run. The difference between the two is set with the keyword allnew in the config file. 1 for a SoFiA run, 2 for pre-produced SoFiA files.
